import { getServerSession } from "next-auth";
import React from "react";
import Login from "../components/Login";
import Navbar from "../components/Navbar";
import { SessionProvider } from "../components/SessionProvider";
import Sidebar from "../components/Sidebar";
import { authOptions } from "../pages/api/auth/[...nextauth]";
import "../styles/globals.css";
import SidebarProvider from "../context/sidebarContext";
import ChatInput from "../components/ChatInput";

export const metadata = {
  title: "ChatGPT Messenger",
  description: "Generated by Next.js",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body className="text-small h-screen">
        <SidebarProvider>
          <SessionProvider session={session}>
            {!session ? (
              <Login />
            ) : (
              <React.Fragment>
                <Navbar />
                <div className="flex">
                  <div className="hidden md:flex">
                    <Sidebar />
                  </div>

                  <div className="bg-background h-[calc(100vh-2.5rem)] md:h-screen flex-1">
                    {children}
                  </div>
                </div>
              </React.Fragment>
            )}
          </SessionProvider>
        </SidebarProvider>
      </body>
    </html>
  );
}
